### ISSUE TITLE
Описание a…z

### ISSUE THREAD

**Issue by Mercury13** [unicode-table/unicode-table-data#109]
Латинские строчные буквы появились в средние века из т.н. минускульного письма, служившего для экономии дорогого пергамента.
В кириллице экономили место по-другому (писали букву над буквой), к тому же часто пользовались более дешёвыми материалами (берёстой), потому в ней нет такого выразительного минускула. Людям из других культур русский кажется сплошной капителью. А вот болгары и сербы позаимствовали часть типографских традиций у Запада, и их шрифт ближе к латинице.

**Comment by asanov** [comment]
👍
