### ISSUE TITLE
Permission to use some data in another application

### ISSUE THREAD

**Issue by jamesohortle** [unicode-table/unicode-table-data#115]
Hi,

I wanted to use the data under `./loc/en/symbols/` for VS Code extension which I am developing. The repo is currently private but will eventually be published.

Please let me know if I have permission to use the data there (easier than processing the data from raw myself).

Cheers.

**Comment by vasa-c** [comment]
Hi, @jamesohortle 
English names of symbol taken from Unicode - https://home.unicode.org/
From UCD - https://unicode.org/ucd/
