### ISSUE TITLE
Recent change to site making sets hard to see?

### ISSUE THREAD

**Issue by KandiPanda** [unicode-table/unicode-table-data#128]
Some recent change to the site has changed the "set" pages from a nice grid of Unicode characters into a complete mess on my screen. Is there at least a style that I can apply in Stylus to make it look the way that it did before?

**Examples:** 

![image](https://user-images.githubusercontent.com/43508599/71317176-df3d4f00-2442-11ea-9526-5eb21f642a1d.png)

![image](https://user-images.githubusercontent.com/43508599/71317178-e6fcf380-2442-11ea-9d35-38923f8c2538.png)

**Comment by a259422-max** [comment]
Bug arreglado
