### ISSUE TITLE
На страницах раздела "Дополнение к латинице — 1" пробела пропала кнопка "Скопировать"

### ISSUE THREAD

**Issue by LidiaMaximova** [unicode-table/unicode-table-data#215]
На страницах раздела "Дополнение к латинице — 1" под картинкой символа раньше была кнопка "Скопировать". Теперь ее нет, поэтому не получается скопировать, например, неразрывный пробел.

**Comment by alex-sutr** [comment]
Мы постараемся решить эту проблему в рамках ближайшего релиза

**Comment by alex-sutr** [comment]
Исправлено в рамках сегодняшнего релиза
