### ISSUE TITLE
I keep facing the fatal error to enter Halfwidth and Fullwidth Forms

### ISSUE THREAD

**Issue by iamkyoko** [unicode-table/unicode-table-data#216]
Not quite sure if there are any patterns but I keep facing the error when I try to find any fullwidth characters on the website.

`Fatal error: gd-webp cannot get webp info in /app/libs/Services/ImageCreators/EntityOgImageCreator.php on line 176`

**Comment by asanov** [comment]
Yes, we have a problem

**Comment by alex-sutr** [comment]
@iamkyoko Can you give link with this error?

**Comment by iamkyoko** [comment]
Sorry for the delay, I've been not facing the error since I posted here. 🙇

I encountered the error when I tried to open the page via search results. Like, I can see the "Fullwidth Digit Zero" page, but I couldn't access the `https://symbl.cc/en/unicode/blocks/halfwidth-and-fullwidth-forms/`

![image](https://github.com/symbl-cc/symbl-data/assets/65995329/c2644e33-96d7-47cb-a7c7-324fa8c1312c)
