### ISSUE TITLE
Wiki outdated for localisation blocks

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [unicode-table/unicode-table-data#27]
Ave!

Thanks for lovely tool that I often use, firstly. ;-)

Onto issue topic: Wiki on localisation blocks is - I think - outdated. It mentions folder `blocks`, none such folder exists. Exact quote:

```
Big texts that need to be translated are stored in the folder blocks. For example, the Russian version of the page "About" is located here: /loc/ru/blocks/about.txt.
```

Please straighten it out, so I can follow up with Polish translation accurately.

**Comment by vasa-c** [comment]
Ave! Yes, the `blocks` folder was removed from the repo.

**Comment by LIttleAncientForestKami** [comment]
Nice to know, I'll proceed accordingly with translation.

**Comment by LIttleAncientForestKami** [comment]
Cut out outdated docs from all three languages (Polish, Russian, English). That way future translations shan't have it.
