### ISSUE TITLE
Main data files Wiki, clarification needed for translation

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [unicode-table/unicode-table-data#28]
Ave! Just noticed during translation that we have common and language-independent used as same meaning. Is that on purpose?

    These files are only for common data (language independent).

This is taken from Main data page, about files in folder `data`. Are they common for all languages or language independent (like, they don't have anything to do with languages so they are not dependent on them).

**Comment by asanov** [comment]
These files are common  for all language versions and contain language-independent data.

**Comment by LIttleAncientForestKami** [comment]
Thanks, translation benefitted from your insight. :-) Closing.
