### ISSUE TITLE
Ophiuchus U+26CE does not display on http://unicode-table.com/en/blocks/miscellaneous-symbols/

### ISSUE THREAD

**Issue by msouth** [unicode-table/unicode-table-data#31]
The display is blank for Ophiuchus (U+26CE) on http://unicode-table.com/en/blocks/miscellaneous-symbols/ , while displaying correctly on http://unicode-table.com/en/26CE/

(hopefully this is the right place for this feedback)

**Comment by vasa-c** [comment]
Hi, @msouth 
We have added an image of this character to the website.
