### ISSUE TITLE
Should "desc" page be translated?

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [unicode-table/unicode-table-data#32]
There is a page that's only in Russian. Do we want it translated to other languages as well?

https://github.com/unicode-table/unicode-table-data/wiki/Desc-(Russian)

My Russian tells me it's about symbols and alphabets (раздела?) and file formats for both.

**Comment by asanov** [comment]
Tomasz, done. Thanks

**Comment by LIttleAncientForestKami** [comment]
OK, I'm also done myself with translation to Polish. Thank you Sergei, having English translation in few places helped tremendously. While I could translate most things myself, I had troubles with some things (осуществляется переносами строк comes to mind :P) Few questions pop up:

1) Doing rest of the pages I spotted that we never link that page in other pages. Did I miss something? Is it linked from somewhere? Because neither index nor other pages link it and it can only be reached through menu. Why?

2) What does "В качестве" mean? "качествo" is quality, but whole think is about URL text. Also, can "заголовoк" be used not as in site title or heading but URL text? Or is it that links in AxyML phrased like 

```
[U:symbolCodeHere myHeadingHere]
```
 will lead to appropriate character page and title it myHeadingHere?

For convenience, link to Polish translation of the page: https://github.com/unicode-table/unicode-table-data/wiki/Desc-(Polish)

**Comment by asanov** [comment]
Tomasz, thank you for your work.

1) because of time we created this page. As I remember we wrote it after all others and forgot to make links.
2) "В качестве" mean "As". For example "Он использовал ящик в качестве стула" : "He used the the box as chair".

**Comment by LIttleAncientForestKami** [comment]
OK I see. Then I've added the links, please take a look and verify (especially Russian! :D):
https://github.com/unicode-table/unicode-table-data/wiki/Index-(English)
https://github.com/unicode-table/unicode-table-data/wiki/Index-(Polish)
https://github.com/unicode-table/unicode-table-data/wiki/Index-(Russian)

If all is well, we can close this as done.

**Comment by asanov** [comment]
I've fixed a little :)

**Comment by LIttleAncientForestKami** [comment]
:+1: I'm relieved. So, plural here was like in Polish. Great, closing.
