### ISSUE TITLE
Использовать универсальный шрифт noto от google

### ISSUE THREAD

**Issue by socketpair** [unicode-table/unicode-table-data#38]
http://www.google.com/get/noto

**Comment by asanov** [comment]
отлично!

**Comment by socketpair** [comment]
И не забыть про начертания (сериф и не сериф, а также жирный и курсивный) у них оно РЕАЛЬНО разное,а не просто наклонено и разжированно автоматом.

**Comment by asanov** [comment]
Да, так и должно быть в нормальных шрифтах. Это очень круто. Спасибо

**Comment by socketpair** [comment]
Эмм. Используется ? Или просто закрыли ?

**Comment by asanov** [comment]
Частично используется. Все символы теперь отображаются.

**Comment by asanov** [comment]
Изменения появятся в ближайших обновлениях.
