### ISSUE TITLE
https://unicode-table.com/en/FEFF/ - additional info

### ISSUE THREAD

**Issue by bkdotcom** [unicode-table/unicode-table-data#45]
Under "additional Information" it should mention that, in it's UTF-8 form, this char is AKA the UTF-8 "Byte Order Mark"

https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8
http://www.fileformat.info/info/unicode/char/feff/index.htm

**Comment by asanov** [comment]
Thank you. Done
