### ISSUE TITLE
Feature request:  enlarge character on mouseover

### ISSUE THREAD

**Issue by bkdotcom** [unicode-table/unicode-table-data#46]
When viewing a block such as
https://unicode-table.com/en/blocks/emoticons/

It would be nice if there were a "popover"/tooltip with  the character enlarged (and also containing a short description). 

Currently each element simple contains a title attribute containing a short description

**Comment by ewerybody** [comment]
This is unicode-table-**data**. This repo is not about the website functionality. I doubt someone dealing with the website will read this here :(

**Comment by vasa-c** [comment]
@ewerybody 
We read everything.
But not everything is in time. :)

**Comment by ewerybody** [comment]
Ah cheers! I just saw there is no explicit repo for the website, right?

**Comment by vasa-c** [comment]
@ewerybody yes, there is not public repo of the website source code.

**Comment by sofya1234** [comment]
:)
