### ISSUE TITLE
About the Language Code

### ISSUE THREAD

**Issue by dqwyy** [unicode-table/unicode-table-data#50]
Hi, I found that `cn`, `jp` and `kr` are used to stand for Chinese, Japanese and Korean here. I don't think it is proper to use [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) to stand for the language. I suggest to use [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) like the other languages. Therefore, I suggest using `zh-CN`, `ja` and `ko` to show "Simplified Chinese (China)", "Japanese" and "Korean".

**Comment by vasa-c** [comment]
We working on this at the moment.
