### ISSUE TITLE
data not in sync with website?

### ISSUE THREAD

**Issue by ewerybody** [unicode-table/unicode-table-data#55]
**Is** the website actually using this data?
When I look at [sets.txt](https://github.com/unicode-table/unicode-table-data/blob/master/data/sets.txt#L45) there are **6** emoji listed!
And [on the website](https://unicode-table.com/en/sets/emoji/) there are **149**!

I mean, I'm thankful for such a data repository but ... I'd rather use up-to-date data! 🤔

**Comment by vasa-c** [comment]
@ewerybody the website is actually using this data.

```
set: ☺, ☹, ☻, 1f600-1f640, 1f645-1f64f, 1f680-1f6c5
```

1f600-1f640 is range of 41 symbols

**Comment by ewerybody** [comment]
Aahhh these are **ranges**!! 😮 Alright my bad. Pardon me.
