### ISSUE TITLE
Cannot find some unicode characters

### ISSUE THREAD

**Issue by rentalhost** [unicode-table/unicode-table-data#56]
For instance, the unicode "⚔️" could not be localized by search. The problem here is because it is not only the "⚔" unicode, but two unicodes. In this case:

    Crossed Swords:         E2 9A 94 +
    Variation Selector-16:  EF B8 8F

So the solution for that is search by first unicode character, then append the next ones as mixing.

For instance:

![image](https://user-images.githubusercontent.com/421851/33941362-8118cbe6-dff9-11e7-90d3-fa67ac0fd7e7.png)

So even that I search by "abc", it should list the "a" as primary subject so "b" and "c" as mixing characters.

**Comment by vasa-c** [comment]
We are working on composed symbols at the moment
