### ISSUE TITLE
Что вообще делать с описаниями символов?

### ISSUE THREAD

**Issue by Mercury13** [unicode-table/unicode-table-data#69]
Я попытался подкорректировать описания символов. Вы их просто взяли и удалили скопом.
Как вообще с этим быть и что делать, если я хочу описать какой-нибудь символ?

**Comment by vasa-c** [comment]
@Mercury13 описания символов у нас по другому теперь лежат и с этим репозиторием не синхронизируются.

Присылайте на почту go.vasac@gmail.com
Или здесь в issues.
Ну или, просто в репу, как раньше добавляйте, мы заберём.

Если планируете в больших объёмах это делать, можем подумать над более удобным способом.
