### ISSUE TITLE
Описание 2044

### ISSUE THREAD

**Issue by Mercury13** [unicode-table/unicode-table-data#98]
Знак используется для вёрстки обыкновенных дробей, при этом числитель делают мельче и выше (на манер верхнего индекса), а знаменатель мельче и ниже: <sup>12</sup>⁄<sub>34</sub>. От традиционной косой черты (002F) отличается углом, близким к 45°, и очень маленькой кегельной площадкой, меньше трети общей ширины символа.

**Comment by asanov** [comment]
👍
